package generate;

import java.io.Serializable;
import lombok.Data;

/**
 * null
 * @TableName person
 */
@Data
public class Person implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-02-26 10:22:27
     */
    private Integer id;

    /**
     * 
     *
     * @mbg.generated 2021-02-26 10:22:27
     */
    private String username;

    /**
     * 
     *
     * @mbg.generated 2021-02-26 10:22:27
     */
    private String phone;

    /**
     * 
     *
     * @mbg.generated 2021-02-26 10:22:27
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person
     *
     * @mbg.generated 2021-02-26 10:22:27
     */
    private static final long serialVersionUID = 1L;
}